spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /**


